<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Medipro_Patient_Service.Test</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.0" />
    <PackageReference Include="JetBrains.Annotations" Version="2024.3.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="Moq" Version="4.20.70" />
    <PackageReference Include="xunit" Version="2.5.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.3" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Medipro_Patient_Service.Api\Medipro_Patient_Service.Api.csproj" />
    <ProjectReference Include="..\Medipro_Patient_Service.Application\Medipro_Patient_Service.Application.csproj" />
    <ProjectReference Include="..\Medipro_Patient_Service.Common\Medipro_Patient_Service.Common.csproj" />
    <ProjectReference Include="..\Medipro_Patient_Service.Domain\Medipro_Patient_Service.Domain.csproj" />
    <ProjectReference Include="..\Medipro_Patient_Service.Infrastructure\Medipro_Patient_Service.Infrastructure.csproj" />
    <ProjectReference Include="..\Medipro_Patient_Service.Persistence\Medipro_Patient_Service.Persistence.csproj" />
  </ItemGroup>
</Project>
